---
title: "Lichen Mapping"
author: "Rosemary Victoria Greensmith"
date: "`r Sys.Date()`"
output: github_document
fontsize: 10pt
mainfont: Montserrat
sansfont: Lilita One
monofont: Courier New
geometry: a4paper, top=30mm, bottom=20mm, left=20mm, right=20mm
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = "center",
  fig.width = 8,
  fig.height = 5)


library(dplyr)
library(sf)
library(rnaturalearth)
library(httr)      # for getting data using API's
library(jsonlite)  # for getting NBN Atlas data


# kernel density map
library(sp) # for setting up the layers to map
library(adehabitatHR)
library(raster)

source("getNBNData.R")
source("occurrenceMap.R")

library(showtext)
# library(ggtext)
# Fonts for plots
# font_add_google("Montserrat", "mont")
# font_add_google("Chivo", "chivo")
font_add_google("Lilita One", "lil")
showtext_auto()
```


## Lichen Occurrences
### Lichen species names

```{r a, echo=FALSE, results='asis'}
# String of species names to loop through
# "Pseudevernia furfuracea" - need to add to nSensitive
nSensitive = c("Evernia prunastri","Usnea sp.",
               "Bryoria sp.","Sphaerophorus globosus","Hypogymnia sp.",
               "Parmelia sp.","Graphis sp.","Ochrolechia androgyna")
# "Punctelia subrudecta" - nTolerant
nTolerant = c("Xanthoria parietina","Xanthoria polycarpa","Xanthoria ucrainica",
              "Physcia adscendens","Physcia tenella",
              "Arthonia radiata","Lecidella elaeochroma","Amandinea punctata",
              "Candelariella reflexa")
indicatorSpp = cbind(nSensitive,nTolerant)
names(indicatorSpp) = c("N Sensitive", "N Tolerant")
indicatorSpp[length(nSensitive)+1,1] = "-"
knitr::kable(indicatorSpp, caption = "Nitrogen Indicator Species")
```

<!-- ### Base map -->

```{r,echo=FALSE}
# Download the base map of UK and surrounding countries --------------------
# CRS is WGS 84
uk_map <- ne_countries(
  scale = "medium",
  returnclass = "sf"
) %>%
  filter(admin %in% c("United Kingdom","Ireland"))

```


<!-- This code displays the raw NBN Atlas data on maps. -->

```{r occurrenceMaps, echo=FALSE}
# --------------------------------------------------------------------------
#                 Maps of records from the NBN Atlas
# --------------------------------------------------------------------------

# Set graphical parameters for the maps
op = par(mfrow=c(2,4), font.lab = 2,
         mar=c(2,2.5,1,0.1)+0.1,
         oma=c(0.01,0.01,2,0.01),xpd=FALSE,family = "lil")

# Get NBN Atlas data and map the records ----------------------------------

for (z in 1:2) {
  if (z == 1){
    indicatorSpp = nSensitive
  } else {
    indicatorSpp = nTolerant
  }
  for (a in 1:length(indicatorSpp)) {
    
    # Get NBN Atlas data --------------------------------------------------
    
    df = getNBNData(indicatorSpp[a],1000)
    
    # Map the records -----------------------------------------------------
    
    # set colour group for maps and main panel plot title
    if(z==1) {
      colGroup = "a"
      mainTitle = "Nitrogen-sensitive Lichen"
    } else {
      colGroup = "b"
      mainTitle = "Nitrogen-tolerant Lichen"
    }
  
    # Produce maps
    occurrenceMap(uk_map,df,colGroup,kdePlot = FALSE,plotTitle = indicatorSpp[a])
    
    # Plot main panel plot title
    if (a == 1) {
      mtext(mainTitle,
          side = 3, line = -0.14, outer = TRUE,col = c("#131713"),
          font = 2,cex = 1.05, family = "lil")
      mtext(Sys.Date(),side = 3, line = -0.9, outer = TRUE, cex = 0.5)
    }
    
    rm(df)
  }
}

```

## Combined species occurrences

```{r combinedData, echo=FALSE}

for (z in 1:2) {
  if (z == 1){
    indicatorSpp = nSensitive
    indSppType = "nSensitive"
  } else {
    indicatorSpp = nTolerant
    indSppType = "nTolerant"
  }
  
  numRecords = 1e4

  for (a in 1:length(indicatorSpp)) {
    if (z == 1 && a == 1) {
      df = getNBNData(indicatorSpp[a],numRecords)
      df2 = data.frame(df$scientificName,
                       df$decimalLongitude,
                       df$decimalLatitude,
                       rep(indSppType, times = length(df[,1]))
                     )
    } else {
      df = getNBNData(indicatorSpp[a],numRecords)
      df2 = rbind(df2,data.frame(
        df$scientificName,
        df$decimalLongitude,
        df$decimalLatitude,
        rep(indSppType, times = length(df[,1]))
                     )
                  )
    }
  }
  df2 = na.omit(df2)
}
colnames(df2) = c("scientificName", "decimalLongitude", "decimalLatitude", "indicatorType")

```


```{r combinedMap, echo=FALSE}

# Plot the maps

op = par(mfrow=c(1,2), font.lab = 2,
         mar=c(2,2,5,5.5)+0.1,
         oma=c(0.01,0.01,2,0.01),xpd=FALSE, family = "lil")

occurrenceMap(uk_map,
             sppDF = subset(df2,
                           indicatorType == "nSensitive",
                           select = c("decimalLongitude","decimalLatitude")),
             colGroup = "a", pointsPlot = FALSE, kdePlot = TRUE,
             plotTitle = "Nitrogen Sensitive Spp."
             )
occurrenceMap(uk_map,
             sppDF = subset(df2,
                           indicatorType == "nTolerant",
                           select = c("decimalLongitude","decimalLatitude")),
             colGroup = "b", pointsPlot = FALSE, kdePlot = TRUE,
             plotTitle = "Nitrogen Tolerant Spp."
             )

```

## Difference between indicator species occurrences

```{r mapDifference, echo = FALSE,message=FALSE}
# Preparing data ----------------------------------------------------------
sdf = data.frame(df2$indicatorType,as.numeric(df2$decimalLongitude),
                 as.numeric(df2$decimalLatitude))
s = SpatialPointsDataFrame(data = na.omit(sdf),coords = sdf[,2:3],proj4string = CRS("EPSG:4326"))

# # Trying to set up boundary
# uk_mapL = uk_map
# coast = ne_coastline()
# coast <-coast[[1,"geometry"]]
# as(st_geometry(coast), "Spatial")
# (ud <- kernelUD(s[,1], same4all = TRUE, grid = 100, boundary = st_geometry(coast)))

# Calculating kernel density ----------------------------------------------
(ud <- kernelUD(s[,1], same4all = TRUE, grid = 1000))

# Calculating difference --------------------------------------------------
udSensitive = raster(ud$nSensitive)
udTolerant = raster(ud$nTolerant)
compareRaster(udSensitive,udTolerant)
rastDiff = udSensitive - udTolerant

# Get masked difference --------------------------------------------------
# projection(rastDiff) <- CRS("+init=EPSG:27700") # sets projection to British National Grid
maskedDiff = mask(rastDiff, uk_map)

# Plot difference --------------------------------------------------

op = par(font.lab = 2,mar=c(2,9,1,9)+0.1,xpd=FALSE, family = "lil")

fun_colour_range <- colorRampPalette(c("#c6787e","#d8dedd","#79c6c0"))   
my_colours <- fun_colour_range(1000)

plot(st_geometry(uk_map),border="#f9fdf9",axes=TRUE,
     xlim=c(-15,5),ylim=c(48.5,61.5),
     col="#d8dedd",cex.axis=0.8)
plot(maskedDiff,col=my_colours, add = TRUE)
plot(st_geometry(uk_map),border="#f9fdf9",add = TRUE)
title(main = "Difference in lichen indicator spp. occurrence",family = "lil",cex.main = 1.1,line = -1)

```

```{r citations, echo = FALSE}
knitr::kable(unique(df$dataProviderName), caption = "NBN Atlas citations")
```